<?php include('header-en.php'); ?>

<style>
    @media (max-width: 768px) {
    .vbox { padding: 10px !important; }
    }
</style>


</div><div id="ajax-content-wrap">
<div class="container-wrap">
<div class="container main-content">
<div class="row">
<div id="fws_68d1623ee8337" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top-level full-width-ns full-width-section" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-xs wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<style>@media only screen and (min-width: 1300px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:700px;}
} @media only screen and (max-width: 1299px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:583.33333333333px;}
} @media only screen and (max-width: 1000px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:500px;}
} @media only screen and (max-width: 690px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:259.25925925926px;}
}</style><div data-midnight="nectar-slider" class="parallax_slider_outer"><div data-transition="slide" data-overall_style="classic" data-flexible-height="" data-animate-in-effect="none" data-fullscreen="false" data-button-sizing="regular" data-button-styling="btn_with_count" data-autorotate="" data-parallax="true" data-parallax-disable-mobile="" data-caption-trans="fade_in_from_bottom" data-parallax-style="bg_only" data-bg-animation="none" data-full-width="true" class="nectar-slider-wrap" id="nectar-slider-instance-1"><div class="swiper-container" data-tho="auto" data-tco="auto" data-pho="auto" data-pco="auto" data-loop="false" data-height="700" data-min-height="" data-arrows="false" data-bullets="false" data-bullet_style="see_through" data-bullet_position="bottom" data-desktop-swipe="false" data-settings=""> <div class="swiper-wrapper"><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(https://agrodova.es/wp-content/uploads/2022/02/careers_bg.png);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>GROW YOUR FUTURE,</span><span>WORK WITH US</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div></div><div class="nectar-slider-loading"> <span class="loading-icon none"> </span></div></div></div></div></div></div></div><div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md vc_hidden-sm wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<style>#nectar-slider-instance-2, #nectar-slider-instance-2 .swiper-container{min-height:550px;}
#nectar-slider-instance-2, #nectar-slider-instance-2 .swiper-container{height:calc( 550 * 100vw / 1600 );}</style><div data-midnight="nectar-slider" class="parallax_slider_outer"><div data-transition="slide" data-overall_style="classic" data-flexible-height="true" data-animate-in-effect="none" data-fullscreen="false" data-button-sizing="regular" data-button-styling="btn_with_count" data-autorotate="" data-parallax="true" data-parallax-disable-mobile="" data-caption-trans="fade_in_from_bottom" data-parallax-style="bg_only" data-bg-animation="none" data-full-width="true" class="nectar-slider-wrap" id="nectar-slider-instance-2"><div class="swiper-container" data-tho="auto" data-tco="auto" data-pho="auto" data-pco="auto" data-loop="false" data-height="550" data-min-height="550" data-arrows="false" data-bullets="false" data-bullet_style="see_through" data-bullet_position="bottom" data-desktop-swipe="false" data-settings=""> <div class="swiper-wrapper"><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(https://agrodova.es/wp-content/uploads/2022/02/careers_bg_responsive.png);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>Grow your future, </span><span>work with us</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div></div><div class="nectar-slider-loading"> <span class="loading-icon none"> </span></div></div></div></div></div></div></div></div></div><div id="fws_68d1623ef3bdb" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_85px top_margin_phone_40px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element" style="margin-top: 20px !important;">
<div class="wpb_wrapper"> <h1 class="title-green"><span class="title-span">WE ARE HIRING!</span></h1></div></div></div></div></div></div></div><div id="fws_68d1623f00643" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row vc_row-o-equal-height vc_row-flex vc_row-o-content-middle top_margin_65px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>At Agrodova we want to help you grow both professionally and personally. The company&#8217;s success is based on its three fundamental pillars: research, quality and collaboration. Working with us you will have the chance to be part of a big, qualified group of people that will help you to develop your career in R&amp;D withing the agri-food sector. Agrodova is searching for new talent to join our worldwide team of professionals.</p></div></div></div></div></div><div class="vc_col-sm-3 vc_hidden-lg vc_hidden-md vc_hidden-sm vc_hidden-xs align-right wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"> <a class="nectar-button small regular extra-color-1 regular-button pl-yellow-button small-btn" style="color: rgba(0,0,0,0.6);" href="#" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff"><span>Job Offers</span></a></div></div></div></div></div><div id="fws_68d1623f01635" data-column-margin="10px" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_40px top_margin_phone_0px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-xs wpb_column column_container vc_column_container col has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-left" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1623f03602" data-midnight="" data-column-margin="10px" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-6 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-video-box" data-color="default-accent-color" data-play-button-size="default" data-border-radius="none" data-hover="defaut" data-shadow="none"><div class="inner-wrap"><a href="https://www.youtube.com/watch?v=bKIagoOiuBA&amp;list=PL5GnkE5LgcFhKGI7T7hlVIm2jHlD_Yd3x" class="full-link pp"></a><img fetchpriority="high" decoding="async" class="nectar-lazy" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D&#039;http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg&#039;%20viewBox%3D&#039;0%200%20812%20405&#039;%2F%3E" data-nectar-img-src="https://agrodova.es/wp-content/uploads/2022/02/v1.png" data-nectar-img-srcset="https://agrodova.es/wp-content/uploads/2022/02/v1.png 812w, https://agrodova.es/wp-content/uploads/2022/02/v1.png 300w, https://agrodova.es/wp-content/uploads/2022/02/v1.png 768w, https://agrodova.es/wp-content/uploads/2022/02/v1.png 670w, https://agrodova.es/wp-content/uploads/2022/02/v1.png 600w" sizes="(max-width: 1000px) 100vw, 1000px" alt="agrodova" width="812" height="405"/></div></div></div></div></div><div class="vc_col-sm-6 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-video-box vbox" data-color="default-accent-color" data-play-button-size="default" data-border-radius="none" data-hover="defaut" data-shadow="none"><div class="inner-wrap"><a href="https://www.youtube.com/watch?v=v0uJXq8Zkb8&amp;list=PL5GnkE5LgcFgauI-SpkfmCiN686NoLnht&amp;index=7" class="full-link pp"></a><img decoding="async" class="nectar-lazy" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D&#039;http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg&#039;%20viewBox%3D&#039;0%200%20812%20405&#039;%2F%3E" data-nectar-img-src="https://agrodova.es/wp-content/uploads/2022/02/v2.png" data-nectar-img-srcset="https://agrodova.es/wp-content/uploads/2022/02/v2.png 812w, https://agrodova.es/wp-content/uploads/2022/02/video2-300x150.png 300w, https://agrodova.es/wp-content/uploads/2022/02/video2-768x383.png 768w, https://agrodova.es/wp-content/uploads/2022/02/video2-670x335.png 670w, https://agrodova.es/wp-content/uploads/2022/02/video2-600x299.png 600w" sizes="(max-width: 1000px) 100vw, 1000px" alt="video preview" width="812" height="405"/><a href="https://www.youtube.com/watch?v=v0uJXq8Zkb8&amp;list=PL5GnkE5LgcFgauI-SpkfmCiN686NoLnht&amp;index=7" data-style="default" data-parent-hover="" data-font-style="p" data-color="default" class="play_button_2 large nectar_video_lightbox pp"><span><span class="screen-reader-text">Play Video</span><span class="play"><span class="inner-wrap inner"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600px" height="800px" x="0px" y="0px" viewBox="0 0 600 800" enable-background="new 0 0 600 800" xml:space="preserve"><path fill="none" d="M0-1.79v800L600,395L0-1.79z"></path> </svg></span></span></span></a></div></div></div></div></div></div></div></div></div></div></div></div><div id="fws_68d1623f052e0" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top top_margin_40px top_margin_phone_0px bottom_margin_phone_40px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md vc_hidden-sm wpb_column column_container vc_column_container col has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-left" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1623f0578c" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div style="margin-bottom: 30px;" class="vc_col-sm-6 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-video-box " data-color="default-accent-color" data-play-button-size="default" data-border-radius="none" data-hover="defaut" data-shadow="none"><div class="inner-wrap"><a href="https://www.youtube.com/watch?v=bKIagoOiuBA&amp;list=PL5GnkE5LgcFhKGI7T7hlVIm2jHlD_Yd3x" class="full-link pp"></a><img fetchpriority="high" decoding="async" class="nectar-lazy" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D&#039;http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg&#039;%20viewBox%3D&#039;0%200%20812%20405&#039;%2F%3E" data-nectar-img-src="https://agrodova.es/wp-content/uploads/2022/02/v11.png" data-nectar-img-srcset="https://agrodova.es/wp-content/uploads/2022/02/v11.png 812w, https://agrodova.es/wp-content/uploads/2022/02/v11.png 300w, https://agrodova.es/wp-content/uploads/2022/02/v11.png 768w, https://agrodova.es/wp-content/uploads/2022/02/v11.png 670w, https://agrodova.es/wp-content/uploads/2022/02/v11.png 600w" sizes="(max-width: 1000px) 100vw, 1000px" alt="video preview" width="812" height="405"/></div></div></div></div></div><div class="vc_col-sm-6 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-video-box vbox" data-color="default-accent-color" data-play-button-size="default" data-border-radius="none" data-hover="defaut" data-shadow="none"><div class="inner-wrap"><a href="https://www.youtube.com/watch?v=v0uJXq8Zkb8&amp;list=PL5GnkE5LgcFgauI-SpkfmCiN686NoLnht&amp;index=7" class="full-link pp"></a><img decoding="async" class="nectar-lazy" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D&#039;http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg&#039;%20viewBox%3D&#039;0%200%20812%20405&#039;%2F%3E" data-nectar-img-src="https://agrodova.es/wp-content/uploads/2022/02/v2.png" data-nectar-img-srcset="https://agrodova.es/wp-content/uploads/2022/02/v2.png 812w, https://agrodova.es/wp-content/uploads/2022/02/video2-300x150.png 300w, https://agrodova.es/wp-content/uploads/2022/02/video2-768x383.png 768w, https://agrodova.es/wp-content/uploads/2022/02/v2.png 670w, https://agrodova.es/wp-content/uploads/2022/02/video2-600x299.png 600w" sizes="(max-width: 1000px) 100vw, 1000px" alt="video preview" width="812" height="405"/><a href="https://www.youtube.com/watch?v=v0uJXq8Zkb8&amp;list=PL5GnkE5LgcFgauI-SpkfmCiN686NoLnht&amp;index=7" data-style="default" data-parent-hover="" data-font-style="p" data-color="default" class="play_button_2 large nectar_video_lightbox pp"><span><span class="screen-reader-text">Play Video</span><span class="play"><span class="inner-wrap inner"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600px" height="800px" x="0px" y="0px" viewBox="0 0 600 800" enable-background="new 0 0 600 800" xml:space="preserve"><path fill="none" d="M0-1.79v800L600,395L0-1.79z"></path> </svg></span></span></span></a></div></div></div></div></div></div></div></div></div></div></div></div><div id="fws_68d1623f067ff" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row center-col top_margin_40px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark center">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding max_width_desktop_1000px inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>Take a look at our list of openings, if you don’t find anything you can fit in, please leave us your resume and we will register it and contact you in case we open new processes.</p> </div></div></div></div></div></div></div>



<?php include('footer-en.php'); ?>