<?php 

include('header-en.php');

?>

</div><div id="ajax-content-wrap">
<div class="container-wrap">
<div class="container main-content">
<div class="row">
<div id="fws_68d1545ee2a39" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top-level full-width-ns full-width-section" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-xs wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<style>#nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{min-height:420px;}</style><div data-midnight="nectar-slider" class="parallax_slider_outer"><div data-transition="slide" data-overall_style="classic" data-flexible-height="true" data-animate-in-effect="none" data-fullscreen="true" data-button-sizing="regular" data-button-styling="btn_with_count" data-autorotate="10000" data-parallax="true" data-parallax-disable-mobile="" data-caption-trans="fade_in_from_bottom" data-parallax-style="bg_only" data-bg-animation="none" data-full-width="true" class="nectar-slider-wrap" id="nectar-slider-instance-1"><div class="swiper-container" data-tho="auto" data-tco="auto" data-pho="auto" data-pco="auto" data-loop="false" data-height="900" data-min-height="420" data-arrows="false" data-bullets="true" data-bullet_style="scale" data-bullet_position="bottom" data-desktop-swipe="false" data-settings=""> <div class="swiper-wrapper"><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="centered" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/test_Cabeceras_web_1920X770PX.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>INNOVATION IN</span><span>PLANT VARIETIES</span></h2><p ><span>Helping growers to leverage the benefits of plant breeding</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="top"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/Cabeceras_web_1920X770PX_3_11_12_23_v2.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>EVERYTHING STARTS </span><span>FROM A PLANT</span></h2><p ><span>Producing plants that perform at their best showing the variety traits</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/Cabeceras_web_1920X770PX_2_11_12_23_v2.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>TECHNICAL</span><span>SUPPORT</span></h2><p ><span>Being part of the grower’s team to leverage the benefits of our varieties</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/Cabeceras_web_1920X770PX_1_11_12_23_v2.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>SUSTAINABLE</span><span>BY NATURE</span></h2><p ><span>Comitted to an environmentally friendly agriculture</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div></div><div class="container normal-container slider-pagination-wrap"><div class="slider-pagination"></div></div><div class="nectar-slider-loading"> <span class="loading-icon none"> </span></div></div></div></div></div></div></div><div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md vc_hidden-sm wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<style>#nectar-slider-instance-2, #nectar-slider-instance-2 .swiper-container{min-height:550px;}
#nectar-slider-instance-2, #nectar-slider-instance-2 .swiper-container{height:calc( 550 * 100vw / 1600 );}</style><div data-midnight="nectar-slider" class="parallax_slider_outer"><div data-transition="slide" data-overall_style="classic" data-flexible-height="true" data-animate-in-effect="none" data-fullscreen="false" data-button-sizing="regular" data-button-styling="btn_with_count" data-autorotate="10000" data-parallax="true" data-parallax-disable-mobile="" data-caption-trans="fade_in_from_bottom" data-parallax-style="bg_only" data-bg-animation="none" data-full-width="true" class="nectar-slider-wrap" id="nectar-slider-instance-2"><div class="swiper-container" data-tho="auto" data-tco="auto" data-pho="auto" data-pco="auto" data-loop="false" data-height="550" data-min-height="550" data-arrows="false" data-bullets="true" data-bullet_style="scale" data-bullet_position="bottom" data-desktop-swipe="false" data-settings=""> <div class="swiper-wrapper"><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/Cabeceras_web_375X539PX_5_11_12_23.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>INNOVATION IN</span><span>PLANT VARIETIES</span></h2><p ><span>Helping growers to leverage the benefits of plant breeding</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/Cabeceras_web_375X539PX_3_11_12_23.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>EVERYTHING STARTS </span><span>FROM A PLANT</span></h2><p ><span>Producing plants that perform at their best showing the variety traits</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/Cabeceras_web_375X539PX_2_11_12_23.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>TECHNICAL</span><span>SUPPORT</span></h2><p ><span>Being part of the grower’s team to leverage the benefits of our varieties</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide white-text-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2023/12/test_Cabeceras_web_375X539PX.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span>SUSTAINABLE</span><span>BY NATURE</span></h2><p ><span>Comitted to an environmentally friendly agriculture</span></p></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div></div><div class="container normal-container slider-pagination-wrap"><div class="slider-pagination"></div></div><div class="nectar-slider-loading"> <span class="loading-icon none"> </span></div></div></div></div></div></div></div></div></div><div id="fws_68d1545f106f3" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row only-ordenador top_margin_5pct top_margin_phone_15px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1545f12684" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-8 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p class="color-green subtitle-big">Our comprehensive and innovative solutions include</p></div></div></div></div></div></div></div></div></div></div></div></div><div id="breeding-experts" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_padding_tablet_60px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="fade-in" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col no-extra-padding bottom_margin_tablet_50px inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <h1 class="title-green"><span class="title-span">BREEDING </span><span class="title-span">EXPERTS</span></h1></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>Innovation can help growers make the most of their crops, meet their challenges and supply the global market of fresh berries, asparagus, garlic and endives.</p> <p>Agrodova is at the beginning of the supply chain working along with growers and retailers to produce the best fresh produce all year round.</p></div></div><div class="wpb_text_column wpb_content_element only-responsive">
<div class="wpb_wrapper"> <p class="color-green subtitle-big">Our comprehensive and innovative solutions include</p></div></div></div></div></div><div class="vc_col-sm-8 col-right-side wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1545f14469" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-fancy-box using-img has-animation" data-style="default" data-animation="fade-in-from-right" data-hover-o="default" data-border-radius="default" data-border="" data-box-color-opacity="1" data-delay="0" data-alignment="left" data-color="accent-color"><div class="box-bg" data-nectar-img-src="wp-content/uploads/2022/02/ryd-planasa.webp"></div><div class="inner" style="min-height: 300px"><a class="nectar-button pl-yellow-button" href="rd">R&amp;D</a></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-fancy-box using-img has-animation" data-style="default" data-animation="fade-in-from-right" data-hover-o="default" data-border-radius="default" data-border="" data-box-color-opacity="1" data-delay="0" data-alignment="left" data-color="accent-color"><div class="box-bg" data-nectar-img-src="wp-content/uploads/2022/02/nursery-planasa.webp"></div><div class="inner" style="min-height: 300px"><a class="nectar-button pl-yellow-button" href="nursery/index">Nursery</a></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-fancy-box using-img has-animation" data-style="default" data-animation="fade-in-from-right" data-hover-o="default" data-border-radius="default" data-border="" data-box-color-opacity="1" data-delay="0" data-alignment="left" data-color="accent-color"><div class="box-bg" data-nectar-img-src="wp-content/uploads/2022/02/technical-support-planasa.webp"></div><div class="inner" style="min-height: 300px"><a class="nectar-button pl-yellow-button" href="technical-support/index">Technical support</a></div></div></div></div></div></div></div></div></div></div></div></div><div id="fws_68d1545f16142" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_5pct bottom_margin_7pct top_margin_tablet_30px top_margin_phone_40px bottom_margin_tablet_50px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1545f166c1" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row" style="padding-bottom: 15px;"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-6 wpb_column column_container vc_column_container col child_column centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p class="color-green subtitle-medium">We leverage key plant traits to develop new breeding varieties that fulfill growers&#8217; commercial and environmental needs.</p> <p class="color-green subtitle-medium">To accomplish this, we have created:</p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div></div></div><div id="fws_68d1545f171ac" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col child_column centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="vc_col-sm-12 vc_hidden-sm vc_hidden-xs col-logos-planasa wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_earliness" target="_self"> <img fetchpriority="high" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="727" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-earlines.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20727%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-earlines.png 727w, wp-content/uploads/2022/02/agrodova-earlines.png 600w, wp-content/uploads/2022/02/agrodova-earlines.png 300w" sizes="(max-width: 727px) 100vw, 727px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_jumbo" target="_self"> <img decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="640" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-jumbo.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20640%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-jumbo.png 640w, wp-content/uploads/2022/02/agrodova-jumbo.png 600w, wp-content/uploads/2022/02/agrodova-jumbo.png 300w" sizes="(max-width: 640px) 100vw, 640px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_premium" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="646" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-premium.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20646%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-premium.png 646w, wp-content/uploads/2022/02/agrodova-premium.png 600w, wp-content/uploads/2022/02/agrodova-premium.png 300w" sizes="auto, (max-width: 646px) 100vw, 646px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_shelf" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="728" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-shelf-life.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20728%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-shelf-life.png 728w, wp-content/uploads/2022/02/agrodova-shelf-life.png 600w, wp-content/uploads/2022/02/agrodova-shelf-life.png 300w" sizes="auto, (max-width: 728px) 100vw, 728px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_yield" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="640" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-yield.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20640%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-yield.png 640w, wp-content/uploads/2022/02/agrodova-yield.png 600w, wp-content/uploads/2022/02/agrodova-yield.png 300w" sizes="auto, (max-width: 640px) 100vw, 640px"/> </a></div></div></div></div></div></div></div></div></div><div id="fws_68d1545f1a75b" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md col-logos-planasa wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_earlinessmv" target="_self"> <img fetchpriority="high" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="727" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-earlines.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20727%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-earlines.png 727w, wp-content/uploads/2022/02/agrodova-earlines.png 600w, wp-content/uploads/2022/02/agrodova-earlines.png 300w" sizes="(max-width: 727px) 100vw, 727px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_jumbomv" target="_self"> <img decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="640" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-jumbo.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20640%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-jumbo.png 640w, wp-content/uploads/2022/02/agrodova-jumbo.png 600w, wp-content/uploads/2022/02/agrodova-jumbo.png 300w" sizes="(max-width: 640px) 100vw, 640px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_premiummv" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="646" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-premium.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20646%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-premium.png 646w, wp-content/uploads/2022/02/agrodova-premium.png 600w, wp-content/uploads/2022/02/agrodova-premium.png 300w" sizes="auto, (max-width: 646px) 100vw, 646px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_shelfmv" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="728" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-shelf-life.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20728%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-shelf-life.png 728w, wp-content/uploads/2022/02/agrodova-shelf-life.png 600w, wp-content/uploads/2022/02/agrodova-shelf-life.png 300w" sizes="auto, (max-width: 728px) 100vw, 728px"/> </a></div></div></div></div><div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="rd#planasa_yieldmv" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="204" width="640" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/02/agrodova-yield.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20640%20204'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/agrodova-yield.png 640w, wp-content/uploads/2022/02/agrodova-yield.png 600w, wp-content/uploads/2022/02/agrodova-yield.png 300w" sizes="auto, (max-width: 640px) 100vw, 640px"/> </a></div></div></div></div></div></div></div></div></div><div id="fws_68d1545f1bf67" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col child_column centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">

<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1545f1cf94" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-8 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element text-our-varieties">
<div class="wpb_wrapper"> <h2 class="title-green title-green-right"><span class="title-span">OUR </span><span class="title-span">VARIETIES</span></h2></div></div></div></div></div></div></div></div></div></div></div></div><div id="our-varieties" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_5pct top_margin_phone_40px bottom_margin_tablet_40px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d1545f1ddef" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row vc_row-o-equal-height vc_row-flex"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/blueberry/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/blueberry-home.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/blueberry-home.webp 800w, https://planasa.com/wp-content/uploads/2022/02/blueberry-home-300x215.webp 300w, https://planasa.com/wp-content/uploads/2022/02/blueberry-home-768x551.webp 768w, https://planasa.com/wp-content/uploads/2022/02/blueberry-home-600x431.webp 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/blueberry/index.html">BLUEBERRY</a></p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/blackberry/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/blackberry-home.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/blackberry-home.webp 800w, https://planasa.com/wp-content/uploads/2022/02/blackberry-home-300x215.webp 300w, https://planasa.com/wp-content/uploads/2022/02/blackberry-home-768x551.webp 768w, https://planasa.com/wp-content/uploads/2022/02/blackberry-home-600x431.webp 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/blackberry/index.html">BLACKBERRY</a></p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/strawberry/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/rapsberry-home.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/rapsberry-home.webp 800w, https://planasa.com/wp-content/uploads/2022/02/rapsberry-home-300x215.webp 300w, https://planasa.com/wp-content/uploads/2022/02/rapsberry-home-768x551.webp 768w, https://planasa.com/wp-content/uploads/2022/02/rapsberry-home-600x431.webp 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/strawberry/index.html">STRAWBERRY</a></p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/raspberry/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/raspberry-home.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/raspberry-home.webp 800w, https://planasa.com/wp-content/uploads/2022/02/raspberry-home-300x215.webp 300w, https://planasa.com/wp-content/uploads/2022/02/raspberry-home-768x551.webp 768w, https://planasa.com/wp-content/uploads/2022/02/raspberry-home-600x431.webp 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/raspberry/index.html">RASPBERRY</a></p></div></div></div></div></div></div></div><div id="fws_68d1545f210ec" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row vc_row-o-equal-height vc_row-flex"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/endibia/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/endives-home.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/endives-home.webp 800w, https://planasa.com/wp-content/uploads/2022/02/endives-home-300x215.webp 300w, https://planasa.com/wp-content/uploads/2022/02/endives-home-768x551.webp 768w, https://planasa.com/wp-content/uploads/2022/02/endives-home-600x431.webp 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/endibia/index.html">ENDIVES</a></p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/asparagus/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/asparagus-home.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/asparagus-home.webp 800w, https://planasa.com/wp-content/uploads/2022/02/asparagus-home-300x215.webp 300w, https://planasa.com/wp-content/uploads/2022/02/asparagus-home-768x551.webp 768w, https://planasa.com/wp-content/uploads/2022/02/asparagus-home-600x431.webp 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/asparagus/index.html">ASPARAGUS</a></p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="product/garlic/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="574" width="800" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/ajo-planasa.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20800%20574'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/ajo-planasa.jpg 800w, https://planasa.com/wp-content/uploads/2022/02/ajo-planasa-300x215.jpg 300w, https://planasa.com/wp-content/uploads/2022/02/ajo-planasa-768x551.jpg 768w, https://planasa.com/wp-content/uploads/2022/02/ajo-planasa-600x431.jpg 600w" sizes="auto, (max-width: 800px) 100vw, 800px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="product/garlic/index.html">GARLIC</a></p></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <a href="avocado/index.html" target="_self"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="287" width="400" data-animation="fade-in" data-nectar-img-src="https://planasa.com/wp-content/uploads/2022/02/Grupo-1026.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20400%20287'%2F%3E" alt="" data-nectar-img-srcset="https://planasa.com/wp-content/uploads/2022/02/Grupo-1026.jpg 400w, https://planasa.com/wp-content/uploads/2022/02/Grupo-1026-300x215.jpg 300w" sizes="auto, (max-width: 400px) 100vw, 400px"/> </a></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><a href="avocado/index.html">AVOCADO</a></p></div></div></div></div></div></div></div></div></div></div></div></div><div id="find-varieties-you-need" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-section vc_row-o-full-height vc_row-o-columns-middle vc_row-o-equal-height vc_row-flex" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" style="background-color: rgba(255,255,255,0);" data-bg-animation="fade-in" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop using-bg-color" style="background-color: rgba(255,255,255,0);"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-6 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="divider-wrap height_tablet_50px height_phone_50px" data-alignment="default"><div style="height: 320px;" class="divider"></div></div><div class="wpb_text_column wpb_content_element text-find-varieties">
<div class="wpb_wrapper">
<div class="title-green title-white"><span class="title-span">FIND THE </span><span class="title-span">VARIETIES </span> <span class="title-span">YOU NEED</span></div></div></div><a class="nectar-button small regular extra-color-1 regular-button pl-yellow-button" style="color: #3f9c35;" href="varieties/index.html" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff"><span>Find it</span></a><div class="divider-wrap height_tablet_0px height_phone_50px" data-alignment="default"><div style="height: 100px;" class="divider"></div></div></div></div></div><div class="vc_col-sm-6 col-form-home wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="divider-wrap height_tablet_0px height_phone_20px" data-alignment="default"><div style="height: 280px;" class="divider"></div></div><div class="wpb_text_column wpb_content_element color-white p-home-contact">
<div class="wpb_wrapper"> <p>DO YOU WANT MORE INFORMATION?</p></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div class="frm_forms with_frm_style frm_style_estilos-formidable" id="frm_form_5_container" data-token="a9d8f072565d43d3649d4af2c4182821">
<form enctype="multipart/form-data" method="post" class="frm-show-form green-form frm_js_validate  frm_pro_form " id="form_contact-home" data-token="a9d8f072565d43d3649d4af2c4182821">
<div class="frm_form_fields">
<fieldset>
<legend class="frm_screen_reader">Contact Home EN</legend>
<div class="frm_fields_container">
<input type="hidden" name="frm_action" value="create" />
<input type="hidden" name="form_id" value="5" />
<input type="hidden" name="frm_hide_fields_5" id="frm_hide_fields_5" value="" />
<input type="hidden" name="form_key" value="contact-home" />
<input type="hidden" name="item_meta[0]" value="" />
<input type="hidden" id="frm_submit_entry_5" name="frm_submit_entry_5" value="64c562c416" /><input type="hidden" name="_wp_http_referer" value="/" /><div id="frm_field_33_container" class="frm_form_field form-field frm_required_field frm_none_container frm_first"> <label for="field_qh4icy2" id="field_qh4icy2_label" class="frm_primary_label">Name <span class="frm_required" aria-hidden="true">*</span> </label> <input type="text" id="field_qh4icy2" name="item_meta[33]" value="" maxlength="90" placeholder="Name*" data-reqmsg="Please provide a name" aria-required="true" data-invmsg="Name is invalid" aria-invalid="false" /></div><div id="frm_field_35_container" class="frm_form_field form-field frm_required_field frm_none_container frm_full"> <label for="field_29yf4d2f8c81eabe8" id="field_29yf4d2f8c81eabe8_label" class="frm_primary_label">Email <span class="frm_required" aria-hidden="true">*</span> </label> <input type="email" id="field_29yf4d2f8c81eabe8" name="item_meta[35]" value="" maxlength="90" placeholder="Email*" data-reqmsg="Please provide an email address" aria-required="true" data-invmsg="Please provide a properly formatted email address" aria-invalid="false" /></div><div id="frm_field_37_container" class="frm_form_field form-field frm_required_field frm_none_container frm_full">
<label for="field_9jv0r12" id="field_9jv0r12_label" class="frm_primary_label">Message
<span class="frm_required" aria-hidden="true">*</span>
</label>
<textarea name="item_meta[37]" id="field_9jv0r12" rows="5"  placeholder="Message*" data-reqmsg="Please fill out this field" aria-required="true" data-invmsg="Message is invalid" aria-invalid="false"  ></textarea></div><input type="hidden" name="item_meta[117]" id="field_s0lza" value="HOME"  data-frmval="HOME"   />
<div id="frm_field_38_container" class="frm_form_field form-field frm_required_field frm_none_container vertical_radio">
<div id="field_ui0ih_label" class="frm_primary_label">Legal <span class="frm_required" aria-hidden="true">*</span></div><div class="frm_opt_container" aria-labelledby="field_ui0ih_label" role="group">		<div class="frm_checkbox" id="frm_checkbox_38-0"> <label for="field_ui0ih-0"> <input type="checkbox" name="item_meta[38][]" id="field_ui0ih-0" value="I have read and agree to the &lt;a href=_/legal-notice/__Terms.html of Use&lt;/a&gt; and &lt;a href=_/privacy-policy/__Privacy.html Policy&lt;/a&gt;." data-reqmsg="Please read and agree to the Terms of Use and Privacy Policy" data-invmsg="Legal is invalid" aria-invalid="false" aria-required="true" /> I have read and agree to the <a href="legal-notice/index.html">Terms of Use</a> and <a href="privacy-policy/index.html">Privacy Policy</a>.</label></div><div class="frm_checkbox" id="frm_checkbox_38-1"> <label for="field_ui0ih-1"> <input type="checkbox" name="item_meta[38][]" id="field_ui0ih-1" value="I have read and accept the following information on data protection: Plantas de Navarra SA (Agrodova), as data controller, informs you that your data is collected for the purpose of managing the company&#039;s internal or external communications, as well as for respond to queries or requests obtained through the forms on the website. The legal basis for the treatment of your data is the consent of the interested party when contacting our organization. Your data will not be transferred to third parties except legal obligation. Any person has the right to request access, rectification, deletion, treatment limitation, opposition or the right to portability of their personal data, by writing to our physical address indicated on the web, or by sending an email to planasa@planasa.com, indicating the right you wish to exercise. You can obtain additional information in our legal notice." data-reqmsg="Please read and agree to the Terms of Use and Privacy Policy" data-invmsg="Legal is invalid" aria-invalid="false" /> I have read and accept the following information on data protection: Plantas de Navarra SA (Agrodova), as data controller, informs you that your data is collected for the purpose of managing the company's internal or external communications, as well as for respond to queries or requests obtained through the forms on the website. The legal basis for the treatment of your data is the consent of the interested party when contacting our organization. Your data will not be transferred to third parties except legal obligation. Any person has the right to request access, rectification, deletion, treatment limitation, opposition or the right to portability of their personal data, by writing to our physical address indicated on the web, or by sending an email to planasa@planasa.com, indicating the right you wish to exercise. You can obtain additional information in our legal notice.</label></div></div></div><input type="hidden" name="item_key" value="" />
<div id="frm_field_384_container"> <label for="field_iwza1" > If you are human, leave this field blank. </label> <input id="field_iwza1" type="text" class="frm_form_field form-field frm_verify" name="item_meta[384]" value="" /></div><input name="frm_state" type="hidden" value="dQWw6f3rmiszXAgKyUWpYpUXk6FgL2sLPMsajZp+Aic0ctn9uMy0NXjTq/LfPzU0" /><div class="frm_submit"> <button class="frm_button_submit frm_final_submit" type="submit" formnovalidate="formnovalidate">Send</button></div></div></fieldset></div></form></div></div></div><div class="divider-wrap height_tablet_40px height_phone_0px" data-alignment="default"><div style="height: 130px;" class="divider"></div></div></div></div></div></div></div><div id="recent-posts" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_tablet_80px top_margin_phone_100px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="fade-in" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div class="planasa-lasts-posts">
<div class="pl-post-item">
<div class="pl-post-header">
<div class="pl-categories"><a href="strawberry/index.html">Strawberry</a></div><div class="time-reading">2 <span>min</span></div></div><a href="planasas-strawberry-varieties-stand-out-in-ifapa-trials-for-their-hardiness-earliness-and-low-water-requirements/index.html">
<div class="pl-post-imagen">
<div class="pl-img" style="background-image:url(wp-content/uploads/2024/07/redsayra.jpg)"></div></div><div class="pl-post-content">
<div class="pl-post-title">Agrodova&#8217;s strawberry varieties stand out in IFAPA trials for their hardiness, earliness and low water requirements</div><div class="pl-post-excerpt">RedSayra and Red Samantha are the Agrodova genetics which have formed part of the research carried out by the Andalusian Institute for Agricultural, Fisheries, Food and Organic Production Research and...</div><div class="pl-footer"></div></div></a></div><div class="pl-post-item">
<div class="pl-post-header">
<div class="pl-categories"><a href="">Varieties</a>, <a href="production/index.html">Production</a>, <a href="retailers/index.html">retailers</a></div><div class="time-reading">1 <span>min</span></div></div>
<div class="pl-post-imagen">
<div class="pl-img" style="background-image:url(wp-content/uploads/2024/03/WhatsApp_Image_2024-03-21_at_12.46.48_2.jpg)"></div></div><div class="pl-post-content">
<div class="pl-post-title">Agrodova varieties arise the interest of major European retailers</div><div class="pl-post-excerpt">Leading retailers and marketers from the United Kingdom and the Netherlands have visited  Agrodova&#8217;s Research and Development (R&amp;D) centre in Huelva, highlighting the growing interest in Agrodova&#8217;s varieties in various...</div><div class="pl-footer"> <a class="nectar-button pl-yellow-button" href="">Read More</a></div></div></a></div><div class="pl-post-item">
<div class="pl-post-header">
<div class="pl-categories"><a href="corporate/index.html">Corporate</a></div><div class="time-reading">2 <span>min</span></div></div><a href="50-years/index.html">
<div class="pl-post-imagen">
<div class="pl-img" style="background-image:url(wp-content/uploads/2023/12/50years-Agrodova-1.jpg)"></div></div><div class="pl-post-content">
<div class="pl-post-title">50 years of Agrodova, a history of innovation</div><div class="pl-post-excerpt">Agrodova is 50 years old. Founded by the Darbonne family and Caja de Navarra, what began in 1973 as a small agricultural company is now, five decades later, a world...</div><div class="pl-footer"> <a class="nectar-button pl-yellow-button" href="50-years/index.html">Read More</a></div></div></a></div></div></div></div></div></div></div></div></div><div id="fws_68d1545f35e54" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_50px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">

<?php
include 'footer-en.php';
?>