<?php 
    include 'header-en.php';
?>

</div><div id="ajax-content-wrap">
<div class="container-wrap">
<div class="container main-content">
<div class="row">
<div id="fws_68d153d2298e9" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top-level" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="divider-wrap height_tablet_120px" data-alignment="default"><div style="height: 160px;" class="divider"></div></div></div></div></div></div></div><div id="fws_68d153d22a4dc" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-10 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-highlighted-text" data-style="full_text" data-exp="default" data-using-custom-color="false" data-animation-delay="false" data-color="" data-color-gradient=""><span class="title-green">EVERYTHING STARTS<br /> FROM A PLANT</span></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>Growers need high quality planting material capable of performing at their best and showing the variety traits: earliness, hardiness, yield…</p> <p>Agrodova brings together different locations and plant formats to deliver the most suitable vegetal material to growers around the world.</p> <p>We use cutting-edge technology to measure different parameters like moisture or yield and we register all the operations that take place during the plant production process.</p></div></div></div></div></div><div class="vc_col-sm-2 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div></div></div><div id="fws_68d153d22b60c" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-sm vc_hidden-xs wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="divider-wrap" data-alignment="default"><div style="height: 80px;" class="divider"></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span style="color: #00000099; font-size: 50px;">WE HAVE <strong style="font-family: 'plsa';">+1500 HECTARES</strong></span><br /> <strong style="font-family: 'plsa';"><span style="color: #00000099; font-size: 22px;">LOCATED IN EIGHT NURSERIES</span></strong></p></div></div><div class="divider-wrap" data-alignment="default"><div style="height: 40px;" class="divider"></div></div></div></div></div></div></div><div id="fws_68d153d22c172" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span style="color: #00000099; font-size: 25px;">WE HAVE <strong style="font-family: 'plsa';">+1500 HECTARES</strong></span><br /> <strong style="font-family: 'plsa';"><span style="color: #00000099; font-size: 10px;">LOCATED IN EIGHT NURSERIES</span></strong></p></div></div></div></div></div></div></div><div id="nursery-img" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-sm vc_hidden-xs wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d153d22e79f" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img fetchpriority="high" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1004.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-1004.jpg 536w, wp-content/uploads/2022/02/Grupo-1004-300x148.jpg 300w" sizes="(max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">SPAIN</span></p></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1007-1.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-1007-1.jpg 536w, wp-content/uploads/2022/02/Grupo-1007-1-300x148.jpg 300w" sizes="(max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">MOROCCO</span></p></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1002.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-1002.jpg 536w, wp-content/uploads/2022/02/Grupo-1002-300x148.jpg 300w" sizes="(max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">POLAND</span></p></div></div></div></div></div></div></div><div id="fws_68d153d23248c" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row" style="padding-top: 40px;"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1005.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-1005.jpg 536w, wp-content/uploads/2022/02/Grupo-1005-300x148.jpg 300w" sizes="auto, (max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">USA</span></p></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1006.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-1006.jpg 536w, wp-content/uploads/2022/02/Grupo-1006-300x148.jpg 300w" sizes="auto, (max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">MEXICO</span></p></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1007.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-1007.jpg 536w, wp-content/uploads/2022/02/Grupo-1007-300x148.jpg 300w" sizes="auto, (max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">PERU</span></p></div></div></div></div></div></div></div><div id="fws_68d153d234d40" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row" style="padding-top: 40px;"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Vivero-Rumania-03-1.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Vivero-Rumania-03-1.jpg 536w, wp-content/uploads/2022/05/Vivero-Rumania-03-1-300x148.jpg 300w" sizes="auto, (max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">ROMANIA</span></p></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="536" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/China.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20536%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/China.png 536w, wp-content/uploads/2022/04/China-300x148.png 300w" sizes="auto, (max-width: 536px) 100vw, 536px"/></div></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span class="sub-contry">CHINA</span></p></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div></div></div></div></div></div></div></div><div id="our-varieties" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_5pct top_margin_phone_40px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d153d237a75" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row vc_row-o-equal-height vc_row-flex vc_custom_1644602683000"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">SPAIN</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/spain-planasa1.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/spain-planasa1.jpg 166w, wp-content/uploads/2022/02/spain-planasa1-150x150.jpg 150w, wp-content/uploads/2022/02/spain-planasa1-100x100.jpg 100w, wp-content/uploads/2022/02/spain-planasa1-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">MOROCCO</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/marocco-mob.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/marocco-mob.jpg 166w, wp-content/uploads/2022/02/marocco-mob-150x150.jpg 150w, wp-content/uploads/2022/02/marocco-mob-100x100.jpg 100w, wp-content/uploads/2022/02/marocco-mob-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">POLAND</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/poland-planasa.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/poland-planasa.jpg 166w, wp-content/uploads/2022/02/poland-planasa-150x150.jpg 150w, wp-content/uploads/2022/02/poland-planasa-100x100.jpg 100w, wp-content/uploads/2022/02/poland-planasa-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">USA</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/eeuu-planasa.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/eeuu-planasa.jpg 166w, wp-content/uploads/2022/02/eeuu-planasa-150x150.jpg 150w, wp-content/uploads/2022/02/eeuu-planasa-100x100.jpg 100w, wp-content/uploads/2022/02/eeuu-planasa-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div></div></div><div id="fws_68d153d23b466" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row vc_row-o-equal-height vc_row-flex vc_custom_1644602541873"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">MEXICO</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/mx-planasa.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/mx-planasa.jpg 166w, wp-content/uploads/2022/02/mx-planasa-150x150.jpg 150w, wp-content/uploads/2022/02/mx-planasa-100x100.jpg 100w, wp-content/uploads/2022/02/mx-planasa-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">PERU</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/maroco-planasa.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/maroco-planasa.jpg 166w, wp-content/uploads/2022/02/maroco-planasa-150x150.jpg 150w, wp-content/uploads/2022/02/maroco-planasa-100x100.jpg 100w, wp-content/uploads/2022/02/maroco-planasa-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">ROMANIA</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap" data-hover-animation="zoom"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/05/romania_mobil.jpg" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/05/romania_mobil.jpg 166w, wp-content/uploads/2022/05/romania_mobil-150x150.jpg 150w, wp-content/uploads/2022/05/romania_mobil-100x100.jpg 100w, wp-content/uploads/2022/05/romania_mobil-140x140.jpg 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div><div class="vc_col-sm-3 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p style="text-align: center;"><span class="sub-contry">CHINA</span></p></div></div><div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="166" width="166" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/04/china_mobil.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20166%20166'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/04/china_mobil.png 166w, wp-content/uploads/2022/04/china_mobil-150x150.png 150w, wp-content/uploads/2022/04/china_mobil-100x100.png 100w, wp-content/uploads/2022/04/china_mobil-140x140.png 140w" sizes="auto, (max-width: 166px) 100vw, 166px"/></div></div></div></div></div></div></div></div></div></div></div></div></div></div><div id="fws_68d153d23e5c2" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-highlighted-text" data-style="full_text" data-exp="default" data-using-custom-color="false" data-animation-delay="false" data-color="" data-color-gradient=""> <h2 style="text-align: center;"><span style="text-align: center; color: #3f9c35; font-weight: 300;">OUR NURSERIES</span></h2></div></div></div></div></div></div><div id="contaimer_map" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top row-map-nursery top_margin_300px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image has-tablet has-phone" style="background-position: center center; background-repeat: no-repeat;" data-nectar-img-src="wp-content/uploads/2022/04/map_test_china_5-2.png"></div><div class="row-bg viewport-tablet using-image" style="background-position: center center; background-repeat: no-repeat;" data-nectar-img-src="wp-content/uploads/2022/04/map_tablet_2.png"></div><div class="row-bg viewport-phone using-image" style="background-position: center center; background-repeat: no-repeat;" data-nectar-img-src="wp-content/uploads/2022/04/map_mobile_ch_1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_1"><a class="nectar-button small regular accent-color regular-button ubicacion_1" style="visibility: visible;" href="#prueba_popup2" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">1</a></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_2"><a class="nectar-button small regular accent-color regular-button ubicacion_2" style="visibility: visible;" href="#prueba_popup3" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">2</a></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_3"><a class="nectar-button small regular accent-color regular-button ubicacion_3" style="visibility: visible;" href="#prueba_popup4" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">3</a></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_4"><a class="nectar-button small regular accent-color regular-button ubicacion_4" style="visibility: visible;" href="#prueba_popup6" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">4</a></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_5"><a class="nectar-button small regular accent-color regular-button ubicacion_5" style="visibility: visible;" href="#prueba_popup7" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">5</a></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_6"><a class="nectar-button small regular accent-color regular-button ubicacion_6" style="visibility: visible;" href="#prueba_popup5" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">6</a></div></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper">
<div id="container_ubi_7"><a class="nectar-button small regular accent-color regular-button ubicacion_8" style="visibility: visible;" href="#prueba_popup8" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff">7</a></div></div></div></div></div></div></div></div><div id="fws_68d153d2415fc" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-section wave-section-nursery top_margin_-65px bottom_margin_-150px zindex-set top_padding_phone_120px bottom_padding_phone_120px top_margin_phone_40px bottom_margin_phone_0px" style="padding-top: 280px; padding-bottom: 280px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding max_width_desktop_650px inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-highlighted-text" data-style="full_text" data-exp="default" data-using-custom-color="false" data-animation-delay="false" data-color="" data-color-gradient="">
<div class="title-green title-white"><span class="title-span">OUR</span><span class="title-span">PLANTS</span></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p><span style="color: #ffffff;">Our plants are delivered in different formats to suit every grower’s needs. Contact us to get information on the available formats.</span></p></div></div><a class="nectar-button small regular extra-color-1 regular-button pl-yellow-button" href="varieties" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff"><span>Check our varieties</span></a></div></div></div></div></div><div id="prueba_popup2" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">SPAIN · NAVARRA</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Agrodova central headquarters, R&amp;D in-vitro laboratory, and endive production plant, Provedis.</strong></p> <p id="text_Modal7">Ctra.San Adrián, km 1 31514 Valtierra (Navarra) SPAIN Tel: (+34) 948 867 700 <a href="https://www.google.es/maps/place/PLANASA/@42.2124091,-1.6710055,17z/data=!3m1!4b1!4m5!3m4!1s0xd5a42b0560d5bd1:0x5b91a6690e2f60f4!8m2!3d42.2124091!4d-1.6688168?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="wpb_text_column wpb_content_element vc_custom_1645527752587 color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">SPAIN · SARIÑENA</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Agrodova central headquarters, R&amp;D in-vitro laboratory, and endive production plant, Provedis.</strong></p> <p id="text_Modal7">Ctra.San Adrián, km 1 31514 Valtierra (Navarra) SPAIN Tel: (+34) 948 867 700 <a href="https://www.google.es/maps/place/PLANASA/@42.2124091,-1.6710055,17z/data=!3m1!4b1!4m5!3m4!1s0xd5a42b0560d5bd1:0x5b91a6690e2f60f4!8m2!3d42.2124091!4d-1.6688168?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="wpb_text_column wpb_content_element vc_custom_1645527760137 color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">SPAIN · SEGOVIA</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Agrodova central headquarters, R&amp;D in-vitro laboratory, and endive production plant, Provedis.</strong></p> <p id="text_Modal7">Ctra.San Adrián, km 1 31514 Valtierra (Navarra) SPAIN Tel: (+34) 948 867 700 <a href="https://www.google.es/maps/place/PLANASA/@42.2124091,-1.6710055,17z/data=!3m1!4b1!4m5!3m4!1s0xd5a42b0560d5bd1:0x5b91a6690e2f60f4!8m2!3d42.2124091!4d-1.6688168?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="divider-wrap height_tablet_150px height_phone_150px" data-alignment="default"><div style="height: 25px;" class="divider"></div></div></div></div></div></div></div><div id="prueba_popup3" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">MOROCCO · KÉNITRA</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Agrodova PÉPINIÈRE MAROC SARL. AU.</strong></p> <p id="text_Modal7">Strawberry plant nursery and the production and processing of asparagus crops, stone fruits and red berries.<br /> Domaine La Confiance N4-km5 avant Sidi Yahya el Gharb BP 1262 – Kénitra – MOROCCO<br /> Tel.: +212 661 196 875<br /> Email : ppm@agrodova.es<br /> <a href="https://www.google.es/maps/place/N4,+Sidi+Yahya+El+Gharb,+Marruecos/@34.3065828,-6.300817,18z/data=!3m1!4b1!4m5!3m4!1s0xda0a9a1a3a0d45d:0xf715e424d8dc3081!8m2!3d34.3066726!4d-6.2996773" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="divider-wrap height_tablet_150px height_phone_150px" data-alignment="default"><div style="height: 25px;" class="divider"></div></div></div></div></div></div></div><div id="prueba_popup4" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">POLAND · GNIEZNO</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Agrodova central headquarters, R&amp;D in-vitro laboratory, and endive production plant, Provedis.</strong></p> <p id="text_Modal7">Nurseries for the production of strawberry plants and asparagus.<br /> Ul. Zwirki i Wigury 31/2, 62- 200 Gniezno POLAND<br /> Tel: (+48) 614 154 020<br /> biuro@planasa.pl<a href="https://www.google.es/maps/place/Żwirki+i+Wigury+31,+62-200+Gniezno,+Polonia/@52.5406821,17.6024237,15z/data=!4m5!3m4!1s0x47049104c46edb3b:0xbc1fd38959b8483a!8m2!3d52.5419587!4d17.60414" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="wpb_text_column wpb_content_element vc_custom_1645531994514 color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">POLAND · OSTROWO</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Nurseries for the production of strawberry plants and asparagus.</strong></p> <p id="text_Modal7">Ostrowo, 10 89-115 Ostrowo POLAND<a href="https://www.google.es/maps/place/Ostrowo+10,+89-115+Ostrowo,+Polonia/@53.2508805,17.6356378,11z/data=!4m5!3m4!1s0x4703a7a9cf1b7cc9:0x62664b03bb404e6e!8m2!3d53.2493739!4d17.6646769" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="wpb_text_column wpb_content_element vc_custom_1645532094617 color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">POLAND · PRZYSIEKA</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Nurseries for the production of strawberry plants and asparagus.</strong></p> <p id="text_Modal7">Przysieka,19 62212 Przysieka <a href="https://www.google.es/maps/place/Przysieka+19%2F4,+62-212+Przysieka,+Polonia/@52.6551415,17.4925287,13z/data=!4m5!3m4!1s0x47048455ca4651ed:0x76c991ab482b8b35!8m2!3d52.653738!4d17.525369 target="rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="divider-wrap height_tablet_150px height_phone_150px" data-alignment="default"><div style="height: 25px;" class="divider"></div></div></div></div></div></div></div><div id="prueba_popup7" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element vc_custom_1645532852108 color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">US · RED BLUFF<br /> Agrodova USA</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Nurseries for the production of strawberry and raspberries plants.</strong></p> <p id="text_Modal7">11781 Golden State Hwy Red Bluff CA 96080<br /> Tel: (+1) 530-527-6200<br /> <a href="https://www.google.es/maps/place/1409+Shady+Dell+Rd,+Macdoel,+CA+96058,+EE.+UU./@41.8627429,-121.9988079,13z/data=!4m5!3m4!1s0x54ceea4c182ce51d:0x5b5d60acf77a3055!8m2!3d41.8657951!4d-121.9570298?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="divider-wrap height_tablet_150px height_phone_150px" data-alignment="default"><div style="height: 25px;" class="divider"></div></div></div></div></div></div></div><div id="prueba_popup5" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">MÉXICO · GUADALAJARA<br /> Agrodova MÉXICO</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Strawberry, raspberry and blueberry nursery. Production of raspberries and blueberries.</strong></p> <p id="text_Modal7">Av Chapalita 1096 Colonia campo de polo Chapalita<br /> Guadalajara Jalisco Cp 44500<br /> www.agrodova.es<br /> <a href="https://www.google.es/maps/place/Av.+Chapalita+1096,+Chapalita,+Guadalajara,+Jal.,+México/@20.6624547,-103.3925659,17z/data=!3m1!4b1!4m5!3m4!1s0x8428ae762aee8967:0x44cb5f1d274cc22d!8m2!3d20.6624497!4d-103.3903772?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="wpb_text_column wpb_content_element vc_custom_1645533214129 color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">MÉXICO · MICHOACÁN<br /> Agrodova MÉXICO</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Strawberry, raspberry and blueberry nursery. Production of raspberries and blueberries.</strong></p> <p id="text_Modal7">Km 0.5 carretera Peribán-Los Reyes Col Camichines Peribán, Michoacán CP 60440 – MEXICO<br /> Tel: +52 1 (354) 541 0141<br /> www.agrodova.es<br /> <a href="https://www.google.es/maps/place/San+Antonio+del+Carmen,+Dolores+Hidalgo+Cuna+de+la+Independencia+Nacional,+Gto.,+México/@21.1721198,-100.9315833,16z/data=!3m1!4b1!4m5!3m4!1s0x842b3efc60e97f51:0x289a07d742b6af1c!8m2!3d21.1720863!4d-100.9256085?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="divider-wrap height_tablet_150px height_phone_150px" data-alignment="default"><div style="height: 25px;" class="divider"></div></div></div></div></div></div></div><div id="prueba_popup6" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">PERU·TRUJILLO</h3></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p id="text_Modal5"><strong>Calle Jorge Chavez s/n C.P.M Mariscal Castilla, distrito de Guadalupe provincia de Pacasmayo, La Libertad.</strong></p> <p id="text_Modal7"><a href="https://www.google.es/maps/place/Av.+Chapalita+1096,+Chapalita,+Guadalajara,+Jal.,+México/@20.6624547,-103.3925659,17z/data=!3m1!4b1!4m5!3m4!1s0x8428ae762aee8967:0x44cb5f1d274cc22d!8m2!3d20.6624497!4d-103.3903772?shorturl=1" target="_blank" rel="noopener"><i id="text_Modal6" class="fa fa-map-marker"><span class="text_Icon_modal">Go to Google Maps</span></i></a></p></div></div><div class="divider-wrap height_tablet_150px height_phone_150px" data-alignment="default"><div style="height: 25px;" class="divider"></div></div></div></div></div></div></div><div id="prueba_popup8" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row custom-modal" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap using-image"><div class="row-bg viewport-desktop using-image using-bg-color" style="background-position: center center; background-repeat: no-repeat; background-color: #ffffff;" data-nectar-img-src="wp-content/uploads/2022/02/pop_up_nursery1.png"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-3 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-9 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element color-green subtitle-modal">
<div class="wpb_wrapper"> <h3 id="text_Modal4">CHINA·YUNNAN</h3></div></div><div class="wpb_text_column wpb_content_element">


<?php
    include 'footer-en.php';
?>