<?php

include("header-en.php");

?>



</div><div id="ajax-content-wrap">
<div class="container-wrap">
<div class="container main-content">
<div class="row">
<div id="fws_68d152f4c5513" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top-level full-width-ns full-width-section green-bullets" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-xs wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<style>@media only screen and (min-width: 1300px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:700px;}
} @media only screen and (max-width: 1299px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:583.33333333333px;}
} @media only screen and (max-width: 1000px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:500px;}
} @media only screen and (max-width: 690px) { #nectar-slider-instance-1, #nectar-slider-instance-1 .swiper-container{height:259.25925925926px;}
}</style><div data-midnight="nectar-slider" class="parallax_slider_outer"><div data-transition="slide" data-overall_style="classic" data-flexible-height="" data-animate-in-effect="none" data-fullscreen="false" data-button-sizing="regular" data-button-styling="btn_with_count" data-autorotate="10000" data-parallax="true" data-parallax-disable-mobile="" data-caption-trans="fade_in_from_bottom" data-parallax-style="bg_only" data-bg-animation="none" data-full-width="true" class="nectar-slider-wrap" id="nectar-slider-instance-1"><div class="swiper-container" data-tho="auto" data-tco="auto" data-pho="auto" data-pco="auto" data-loop="false" data-height="700" data-min-height="" data-arrows="false" data-bullets="true" data-bullet_style="see_through" data-bullet_position="bottom" data-desktop-swipe="false" data-settings=""> <div class="swiper-wrapper"><div class="swiper-slide row-slide-rd" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/02/PORTADA_RD-1.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span class="title-green-30 text-success" style="color: green !important;">RESEARCH AND<br>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/04/slider-ryd_1.webp);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span class="title-green-30 text-success" style="color: green !important;">RESEARCH AND<br>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/04/slider-ryd_2.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span class="title-green-30 text-success" style="color: green !important;">RESEARCH AND<br>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/04/slider-ryd_3.webp);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el"><span class="title-green-30 text-success" style="color: green !important;">RESEARCH AND<br>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div></div><div class="container normal-container slider-pagination-wrap"><div class="slider-pagination"></div></div><div class="nectar-slider-loading"> <span class="loading-icon none"> </span></div></div></div></div><div class="divider-wrap height_phone_30px" data-alignment="default"><div style="height: 40px;" class="divider"></div></div></div></div></div><div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md vc_hidden-sm wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<style>#nectar-slider-instance-2, #nectar-slider-instance-2 .swiper-container{min-height:550px;}
#nectar-slider-instance-2, #nectar-slider-instance-2 .swiper-container{height:calc( 550 * 100vw / 1600 );}</style><div data-midnight="nectar-slider" class="parallax_slider_outer"><div data-transition="slide" data-overall_style="classic" data-flexible-height="true" data-animate-in-effect="none" data-fullscreen="false" data-button-sizing="regular" data-button-styling="btn_with_count" data-autorotate="10000" data-parallax="true" data-parallax-disable-mobile="" data-caption-trans="fade_in_from_bottom" data-parallax-style="bg_only" data-bg-animation="none" data-full-width="true" class="nectar-slider-wrap" id="nectar-slider-instance-2"><div class="swiper-container" data-tho="auto" data-tco="auto" data-pho="auto" data-pco="auto" data-loop="false" data-height="550" data-min-height="550" data-arrows="false" data-bullets="true" data-bullet_style="see_through" data-bullet_position="bottom" data-desktop-swipe="false" data-settings=""> <div class="swiper-wrapper"><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/02/Grupo-835.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el" style="color: green !important;"><span>RESEARCH AND</span><span>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/04/slider-ryd_1-mobile.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el" style="color: green !important;"><span>RESEARCH AND</span><span>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/04/slider-ryd_2-mobile.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el" style="color: green !important;"><span>RESEARCH AND<br>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div><div class="swiper-slide" data-desktop-content-width="auto" data-tablet-content-width="auto" data-bg-alignment="center" data-color-scheme="light" data-x-pos="left" data-y-pos="middle"><div class="slide-bg-wrap"><div class="image-bg" style="background-image: url(wp-content/uploads/2022/04/slider-ryd_3-mobile.jpg);"> &nbsp;</div></div><div class="container">
<div class="content"><h2 class="ns-heading-el" style="color: green !important;"><span>RESEARCH AND</span><span>DEVELOPMENT</span></h2></div></div><div class="video-texture"> <span class="ie-fix"></span></div></div></div><div class="container normal-container slider-pagination-wrap"><div class="slider-pagination"></div></div><div class="nectar-slider-loading"> <span class="loading-icon none"> </span></div></div></div></div><div class="divider-wrap height_phone_30px" data-alignment="default"><div style="height: 40px;" class="divider"></div></div></div></div></div></div></div><div id="fws_68d152f4eddd8" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>Innovation is an essential part of Agrodova&#8217;s DNA, this is why we allocate a significant amount of financial and human resources to our R+D.<br /> The main objective is to develop new varieties with unique characteristics for both growers and consumers.</p></div></div></div></div></div></div></div><div id="fws_68d152f4ee89a" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_margin_45px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d152f4f0709" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row ryd-iconos-counter"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 center">
<div class="vc_col-sm-3 vc_hidden-sm vc_col-xs-6 vc_hidden-xs wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div><div class="vc_col-sm-2 vc_col-xs-6 wpb_column column_container vc_column_container col child_column centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img decoding="async" class="img-with-animation skip-lazy ryd-counter-img nectar-lazy" data-delay="0" height="184" width="155" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/varieties.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20155%20184'%2F%3E" alt=""/></div></div></div></div><div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="counter-space"><div class="counter-about"><b>+<span class="counter">225</span></b><br>registered varieties</div></div></div></div></div></div></div><div class="vc_col-sm-2 vc_col-xs-6 wpb_column column_container vc_column_container col child_column centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img decoding="async" class="img-with-animation skip-lazy ryd-counter-img-2 nectar-lazy" data-delay="0" height="184" width="155" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/RD.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20155%20184'%2F%3E" alt=""/></div></div></div></div><div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="counter-space"><div class="counter-about"><b><span class="counter">4</span></b><br>research centres</div></div></div></div></div></div></div><div class="vc_col-sm-2 wpb_column column_container vc_column_container col child_column centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap center" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img decoding="async" class="img-with-animation skip-lazy ryd-counter-img-3 nectar-lazy" data-delay="0" height="184" width="155" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/MILLIONS.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20155%20184'%2F%3E" alt=""/></div></div></div></div><div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="counter-space"><div class="counter-about"><b>+<span class="counter">25</span></b> M€<br>invested in the last 5 years</div></div></div></div></div></div></div><div class="vc_col-sm-3 vc_hidden-sm vc_hidden-xs wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper"></div></div></div></div></div></div></div></div></div></div><div id="fws_68d152f4f3fea" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row bottom_margin_65px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>We have four research centres and development plots in different climatic areas to observe and experiment with new selections.<br /> This allows us to test and offer a wide catalogue of varieties.</p></div></div></div></div></div></div></div><div id="fws_68d152f500653" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row bottom_margin_65px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col centered-text no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d152f500cb8" data-midnight="" data-column-margin="default" class="wpb_row vc_row-fluid vc_row inner_row"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="535" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/04/ryd-image-planasa-4.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20535%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/04/ryd-image-planasa-4.webp 535w, wp-content/uploads/2022/04/ryd-image-planasa-4-300x149.webp 300w" sizes="auto, (max-width: 535px) 100vw, 535px"/></div></div></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="535" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/04/ryd-image-planasa-2.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20535%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/04/ryd-image-planasa-2.webp 535w, wp-content/uploads/2022/04/ryd-image-planasa-2-300x149.webp 300w" sizes="auto, (max-width: 535px) 100vw, 535px"/></div></div></div></div></div></div></div><div class="vc_col-sm-4 wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="img-with-aniamtion-wrap" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in-from-bottom">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy nectar-lazy" data-delay="0" height="265" width="535" data-animation="fade-in-from-bottom" data-nectar-img-src="wp-content/uploads/2022/04/ryd-image-planasa-1.webp" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20535%20265'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/04/ryd-image-planasa-1.webp 535w, wp-content/uploads/2022/04/ryd-image-planasa-1-300x149.webp 300w" sizes="auto, (max-width: 535px) 100vw, 535px"/></div></div></div></div></div></div></div></div></div></div></div></div></div></div><div id="planasa_earliness" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d152f504581" data-midnight="" data-column-margin="none" class="wpb_row vc_row-fluid vc_row inner_row vc_row-o-equal-height vc_row-flex vc_row-o-content-bottom"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-6 ryd-logo-genetics wpb_column column_container vc_column_container col child_column no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="nectar-highlighted-text" data-style="full_text" data-exp="default" data-using-custom-color="false" data-animation-delay="false" data-color="" data-color-gradient=""><span class="title-green">WE HAVE<br /> DEVELOPED</span></div><div class="img-with-aniamtion-wrap custom-size" data-max-width="100%" data-max-width-mobile="default" data-shadow="none" data-animation="fade-in">
<div class="inner">
<div class="hover-wrap"> 
<div class="hover-wrap-inner"> <img loading="lazy" decoding="async" class="img-with-animation skip-lazy margin-left nectar-lazy" data-delay="0" height="93" width="300" data-animation="fade-in" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-747-300x93.png" src="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20300%2093'%2F%3E" alt="" data-nectar-img-srcset="wp-content/uploads/2022/02/Grupo-747-300x93.png 300w, wp-content/uploads/2022/02/Grupo-747.png 382w" sizes="auto, (max-width: 300px) 100vw, 300px"/></div></div></div></div></div></div></div><div class="vc_col-sm-6 vc_hidden-sm vc_hidden-xs wpb_column column_container vc_column_container col child_column has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-right" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-842.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd">
<div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-earlines-1.png" width: 260px; alt=""></div><div><p>EARLY VARIETIES TO PRODUCE IN STRATEGIC WINDOWS</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div><div id="planasa_premium" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row bottom_margin_0px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div id="fws_68d152f5067cc" data-midnight="" data-column-margin="none" class="wpb_row vc_row-fluid vc_row inner_row bottom_padding_phone_40px" style="padding-bottom: 20px;"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-6 wpb_column column_container vc_column_container col child_column padding-3-percent inherit_tablet inherit_phone" data-padding-pos="right" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element vc_custom_1644608114536">
<div class="wpb_wrapper"> <p>In a pre-breeding stage, we study the genome of our gene bank searching for biomolecular markers associated to traits such as earliness, yield or appearance to accelerate the breeding process.</p> <p>We start with X seedlings and select, according to the results of the molecular analysis and breeder’s phenotyping, the individuals that stand out, and crossbreed them to obtain what we call the Agrodova Genetics®.</p></div></div></div></div></div><div class="vc_col-sm-6 vc_hidden-sm vc_hidden-xs wpb_column column_container vc_column_container col child_column has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-right" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1169.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd-rigth">
<div><p id="premium">VARIETIES THAT PRODUCE PREMIUM FRUIT THAT STAND OUT FOR FLAVOUR AND APPEARANCE</p></div><div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-premium-1.png" width:260px; alt=""></div></div></div></div></div></div></div></div></div><div id="fws_68d152f507956" data-midnight="" data-column-margin="none" class="wpb_row vc_row-fluid vc_row inner_row no-padding-column"><div class="row-bg-wrap"> <div class="row-bg"></div></div><div class="row_col_wrap_12_inner col span_12 left">
<div class="vc_col-sm-6 vc_hidden-sm vc_hidden-xs card-planasa-logos-lf wpb_column column_container vc_column_container col child_column has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-left" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-846.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html" id="planasa_yield">
<div class="wpb_wrapper">
<div class="box-rd-rigth">
<div><p>VERY PRODUCTIVE VARIETIES TO HARVEST LARGE/CONCENTRATED VOLUMES</p></div><div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-yield-1.png" width: 260px; alt=""></div></div></div></div></div></div></div><div class="vc_col-sm-6 vc_hidden-sm vc_hidden-xs card-planasa-logos-rg wpb_column column_container vc_column_container col child_column has-animation no-extra-padding inherit_tablet inherit_phone" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-right" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-844.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html" id="planasa_shelf">
<div class="wpb_wrapper">
<div class="box-rd">
<div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-shelf-1.png" width: 260px; alt=""></div><div><p>VARIETIES SPECIALLY CHOSEN FOR THEIR EXPORTATION CAPACITY</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div><div id="planasa_earlinessmv" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-842.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd">
<div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-earlines-1.png" width: 260px; alt=""></div><div><p id="erly">EARLY VARIETIES TO PRODUCE IN STRATEGIC WINDOWS</p></div></div></div></div></div></div></div></div></div><div id="planasa_premiummv" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-1169.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd-rigth">
<div><p id="premium">VARIETIES THAT PRODUCE PREMIUM FRUIT THAT STAND OUT FOR FLAVOUR AND APPEARANCE</p></div><div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-premium-1.png" width:260px; alt=""></div></div></div></div></div></div></div></div></div><div id="fws_68d152f50a5d1" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row top_padding_phone_40px bottom_padding_phone_40px" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="divider-wrap height_phone_20px" data-alignment="default"><div style="height: 20px;" class="divider"></div></div><div class="wpb_text_column wpb_content_element">
<div class="wpb_wrapper"> <p>Our breeding programs aim to develop varieties that better suit the needs of growers, retailers, and end-consumers all over the world. We work today in the food of the future.</p></div></div><a class="nectar-button small regular extra-color-1 regular-button pl-yellow-button" href="varieties" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff"><span>Check our varieties</span></a></div></div></div></div></div><div id="planasa_shelfmv" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-844.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd">
<div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-shelf-1.png" width: 260px; alt=""></div><div><p>VARIETIES SPECIALLY CHOSEN FOR THEIR EXPORTATION CAPACITY</p></div></div></div></div></div></div></div></div></div><div id="planasa_yieldmv" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-846.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd-rigth">
<div><p>VERY PRODUCTIVE VARIETIES TO HARVEST LARGE/CONCENTRATED VOLUMES</p></div><div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-yield-1.png" width: 260px; alt=""></div></div></div></div></div></div></div></div></div><div id="planasa_jumbomv" data-column-margin="default" data-midnight="dark" class="wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex vc_row-o-content-top" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-12 vc_hidden-lg vc_hidden-md wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-847.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd">
<div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-jumbo-1.png" width: 260px; alt="" id="jumbo"></div><div><p id="jumbo-text">BIG VARIETIES THAT STAND OUT IN SIZE</p></div></div></div></div></div></div></div></div></div><div id="planasa_jumbo" data-column-margin="none" data-midnight="dark" class="wpb_row vc_row-fluid vc_row" style="padding-top: 0px; padding-bottom: 0px;"><div class="row-bg-wrap" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="row-bg viewport-desktop"></div></div></div><div class="row_col_wrap_12 col span_12 dark left">
<div class="vc_col-sm-6 vc_hidden-sm vc_hidden-xs wpb_column column_container vc_column_container col has-animation no-extra-padding inherit_tablet inherit_phone mobile-disable-entrance-animation" data-using-bg="true" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="fade-in-from-left" data-delay="0">
<div class="vc_column-inner"><div class="column-image-bg-wrap column-bg-layer viewport-desktop" data-bg-pos="center center" data-bg-animation="none" data-bg-overlay="false"><div class="inner-wrap"><div class="column-image-bg" data-nectar-img-src="wp-content/uploads/2022/02/Grupo-847.jpg"></div></div></div><div class="wpb_wrapper">
<div class="wpb_raw_code wpb_content_element wpb_raw_html">
<div class="wpb_wrapper">
<div class="box-rd">
<div><img decoding="async" src="wp-content/uploads/2022/02/agrodova-jumbo-1.png" width: 260px; alt="" id="jumbo"></div><div><p >BIG VARIETIES THAT STAND OUT IN SIZE</p></div></div></div></div></div></div></div><div class="vc_col-sm-6 vc_hidden-sm vc_hidden-xs ryd-custom-padding wpb_column column_container vc_column_container col no-extra-padding inherit_tablet inherit_phone" data-padding-pos="all" data-has-bg-color="false" data-bg-color="" data-bg-opacity="1" data-animation="" data-delay="0">
<div class="vc_column-inner">
<div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element">


<?php include 'footer-en.php'; ?>